/**
 * Browser-compatible migration runner for PGlite
 *
 * This module handles running database migrations in the browser.
 * Migrations are exported as JSON from the Drizzle migrations folder.
 *
 * How it works:
 * 1. Check current migration version in _migrations table
 * 2. Apply any pending migrations from migrations.json
 * 3. Track applied migrations in _migrations table
 *
 * Note: This is different from server migrations which use drizzle-kit migrate.
 * Browser can't use Node.js fs/path APIs, so we use JSON export instead.
 */

import type { PGlite } from "@electric-sql/pglite";

// Migration structure from Drizzle's migrations.json
interface DrizzleMigration {
  sql: string[]; // Array of SQL statements
  bps: boolean;
  folderMillis: number;
  hash: string;
}

// Import migrations JSON (will be generated by export-migrations.ts)
// If this file doesn't exist yet, it will be created when you run db:generate:client
let migrations: DrizzleMigration[] = [];

try {
  const imported = await import(
    "../../../../drizzle/migrations-client/migrations.json"
  );
  // Handle both default export and direct export (dynamic import returns module object)
  const migrationData = imported.default || imported;
  // Ensure it's actually an array
  if (Array.isArray(migrationData)) {
    migrations = migrationData;
  } else {
    console.warn("[Migrations] Imported migrations is not an array, using empty array");
    migrations = [];
  }
} catch (error) {
  console.warn(
    "[Migrations] No migrations.json found. Run `pnpm db:generate:client` to create it."
  );
  // Empty migrations array - no migrations to run
  migrations = [];
}

/**
 * Run all pending migrations
 *
 * @param client - PGlite client instance
 */
export async function runMigrations(client: PGlite): Promise<void> {
  try {
    console.log("[Migrations] Starting migration process...");

    // Create migrations tracking table if it doesn't exist
    await createMigrationsTable(client);

    // Get current migration version
    const currentVersion = await getCurrentVersion(client);
    console.log(`[Migrations] Current version: ${currentVersion}`);

    // Calculate pending migrations
    const pendingMigrations = migrations.slice(currentVersion);

    if (pendingMigrations.length === 0) {
      console.log(
        "[Migrations] No pending migrations. Database is up to date."
      );
      return;
    }

    console.log(
      `[Migrations] Found ${pendingMigrations.length} pending migration(s)`
    );

    // Apply each pending migration
    for (let i = 0; i < pendingMigrations.length; i++) {
      const migration = pendingMigrations[i];
      const version = currentVersion + i + 1;

      try {
        console.log(
          `[Migrations] Applying migration ${version}/${migrations.length}...`
        );

        // Execute all SQL statements in the migration
        for (const sqlStatement of migration.sql) {
          await client.exec(sqlStatement);
        }

        // Record successful migration
        await recordMigration(client, version);

        console.log(`[Migrations] ✓ Migration ${version} applied successfully`);
      } catch (error) {
        console.error(
          `[Migrations] ✗ Failed to apply migration ${version}:`,
          error
        );
        throw new Error(
          `Migration ${version} failed: ${error instanceof Error ? error.message : "Unknown error"}`
        );
      }
    }

    console.log(
      `[Migrations] ✅ All migrations applied successfully (${migrations.length} total)`
    );
  } catch (error) {
    console.error("[Migrations] Migration process failed:", error);
    throw error;
  }
}

/**
 * Create the migrations tracking table
 *
 * This table stores which migrations have been applied.
 * Simple structure: id (auto-increment), version (unique), applied_at (timestamp)
 */
async function createMigrationsTable(client: PGlite): Promise<void> {
  await client.exec(`
    CREATE TABLE IF NOT EXISTS _migrations (
      id SERIAL PRIMARY KEY,
      version INTEGER NOT NULL UNIQUE,
      applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `);
}

/**
 * Get the current migration version
 *
 * @returns The highest version number from _migrations table, or 0 if none applied
 */
async function getCurrentVersion(client: PGlite): Promise<number> {
  try {
    const result = await client.query<{ version: number }>(
      "SELECT version FROM _migrations ORDER BY version DESC LIMIT 1"
    );

    if (result.rows.length === 0) {
      return 0; // No migrations applied yet
    }

    return result.rows[0].version;
  } catch (error) {
    console.error("[Migrations] Error getting current version:", error);
    return 0;
  }
}

/**
 * Record a successfully applied migration
 *
 * @param client - PGlite client
 * @param version - Migration version number
 */
async function recordMigration(client: PGlite, version: number): Promise<void> {
  await client.query("INSERT INTO _migrations (version) VALUES ($1)", [
    version,
  ]);
}

/**
 * Get migration status
 *
 * Useful for debugging or showing migration info to users.
 *
 * @returns Migration status information
 */
export async function getMigrationStatus(client: PGlite): Promise<{
  current: number;
  total: number;
  pending: number;
  isUpToDate: boolean;
}> {
  await createMigrationsTable(client);
  const current = await getCurrentVersion(client);
  const total = migrations.length;
  const pending = Math.max(0, total - current);

  return {
    current,
    total,
    pending,
    isUpToDate: pending === 0,
  };
}

/**
 * Reset all migrations (for testing)
 *
 * WARNING: This drops the _migrations table and all data!
 * Only use in development/testing.
 */
export async function resetMigrations(client: PGlite): Promise<void> {
  if (process.env.NODE_ENV === "production") {
    throw new Error("Cannot reset migrations in production!");
  }

  await client.exec("DROP TABLE IF EXISTS _migrations CASCADE;");
  console.log("[Migrations] Migration history reset");
}
